title: "Course Syllabus"
remote_theme: pmarsceill/just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: "light"

# Enable or disable the site search
search_enabled: true
# Display the relative url in search results
rel_url: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/uni_icon.png"

plugins:
  - jekyll-spaceship
